# Linear regression code alongs

In [2]:
import pandas as pd

df = pd.read_csv("../../data/Advertising.csv", index_col=0)
df.head()

TV  radio  newspaper  sales
0                                
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [3]:
df.shape

(200, 4)

In [4]:
X, y = df.drop("sales", axis=1), df["sales"]
X.head()

TV  radio  newspaper
0                         
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [5]:
y.head()

0
1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: sales, dtype: float64

## Scikit learn steps

1. Train/Test split - some cases train/validation/test - split
2. Scale the dataset
    - many algorithms require scaling, some dont't
    - wich type of scaling to use? 
    - scale training data, test data to the training data, to avoid data leakage

3. Fit the alorithm to the training data
4. Transform the training data, transform test data
5. Calculate evalutaion metrics

## Train/test split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

In [7]:
X_train.head()

TV  radio  newspaper
0                           
80   116.0    7.7       23.1
198  177.0    9.3        6.4
39    43.1   26.7       35.1
25    62.3   12.6       18.3
123  224.0    2.4       15.6

In [8]:
X_test

TV  radio  newspaper
0                           
96   163.3   31.6       52.9
16   195.4   47.7       52.9
31   292.9   28.3       43.2
159   11.7   36.9       45.2
129  220.3   49.0        3.2
116   75.1   35.0       52.7
70   216.8   43.9       27.2
171   50.0   11.6       18.4
175  222.4    3.4       13.1
46   175.1   22.5       31.5
67    31.5   24.6        2.2
183   56.2    5.7       29.7
166  234.5    3.4       84.8
79     5.4   29.9        9.4
187  139.5    2.1       26.6
178  170.2    7.8       35.2
57     7.3   28.1       41.4
153  197.6   23.3       14.2
83    75.3   20.3       32.5
69   237.4   27.5       11.0
125  229.5   32.3       74.2
17    67.8   36.6      114.0
149   38.0   40.3       11.9
94   250.9   36.5       72.3
66    69.0    9.3        0.9
61    53.5    2.0       21.4
85   213.5   43.0       33.8
68   139.3   14.5       10.2
126   87.2   11.8       25.9
133    8.4   27.2        2.1
10   199.8    2.6       21.2
19    69.2   20.5       18.3
56   198.9   49.4       60.0
76    16.9   43.7       89.4
151  280.7   13.9       37.0
105  238.2   34.3        5.3
136   48.3   47.0        8.5
138  273.7   28.9       59.7
165  117.2   14.7        5.4
77    27.5    1.6       20.7

In [9]:
y_train.shape, y_test.shape

((160,), (40,))

## 2 Feature scaling

- min-max scaling
- values tranformed into 0 to 1

In [10]:


from sklearn.preprocessing import MinMaxScaler
#instansierar en isntans från minmaxscaler
scaler = MinMaxScaler()


scaler

MinMaxScaler()

In [11]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train.shape, scaled_X_test.shape

NotFittedError: This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
scaled_X_train.min(), scaled_X_train.max()


(np.float64(0.0), np.float64(1.0))

In [ ]:
scaled_X_test.min(), scaled_X_test.max()


(np.float64(0.005964214711729622), np.float64(1.1302186878727631))

## Linear regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model

LinearRegression()

In [ ]:
model.fit(scaled_X_train, y_train)
model.coef_

array([13.20747617,  9.75285112,  0.61108329])

## PRediction

In [ ]:
test_sample_feature = scaled_X_test[0].reshape(1, -1)
test_sample_target = y_test.values[0]
test_sample_feature, test_sample_target

(array([[0.54988164, 0.63709677, 0.52286282]]), np.float64(16.9))

In [ ]:
model.predict(test_sample_feature)

array([16.58673085])

In [ ]:
test_sample_target

np.float64(16.9)

## prediction on test data

In [ ]:
y_pred = model.predict(scaled_X_test)
y_pred.shape

(66,)

In [ ]:
y_test.shape

(66,)

In [ ]:
y_pred[:5]

array([16.58673085, 21.18622524, 21.66752973, 10.81086512, 22.25210881])

In [ ]:
y_test[:5].values

array([16.9, 22.4, 21.4,  7.3, 24.7])

## Evaluation

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = :.2f}")
print(f"{mse = :.2f}")
print(f"{rmse = :.2f}")


mae = 1.49
mse = 3.73
rmse = 1.93
